### ISSUE TITLE
Expression expected when creating new generic instance of jsweet.lang.Array

### ISSUE THREAD

**Issue by chrismiddleton** [cincheo/jsweet#198] opened 2016-12-19 20:16 UTC
I was getting an error of "expression expected" in my code and could not find any issue with the Java itself. When trying to make a MWE of the problem, I managed to get this to fail:

The following code gives an error during (I think) the TypeScript compilation phase:

	import jsweet.lang.Array;

	public class Vector<E> {

		class ArrayEnumeration<E> {
			private Array<E> a;
			private int s;
			public ArrayEnumeration (Array<E> a, int s) {
			}
			public void print () {
				System.out.println(a.$get(0));
			}
		}
	
		private Array<E> arr;
		private int size;
	
		public Vector () {
			arr = new Array<>();
			size++;
		}
	
		public void add (E e) {
			arr.push(e);
		}
	
		public void demo () {
			ArrayEnumeration<E> ae = elements();
			ae.print();
		}
	
		public ArrayEnumeration<E> elements () {
			return new ArrayEnumeration<E>(new Array<E>(arr.slice()), size);
		}
	
		public static void main () {
			Vector v = new Vector<String>();
			v.add("Hello, world");
			v.demo();
		}
	
	}

If you run the above in the jsweet sandbox, you'll see what I mean.

The error message is also a little confusing, as it gives the error line as the line that the class itself starts on, whereas the error appears to originate on this line, when running the output through the TypeScript compiler:

    return new ArrayEnumeration<E>(new Array<E>(arr.slice()), size);

The resulting TypeScript looks similar to this:

                return <any>(new Vector.ArrayEnumeration<E>(this, <any>new (__Function.prototype.bind.apply(Array<E>, [null].concat(<any[]>this.arr.slice()))), this.sz));

The error says that there should be an expression after "Array<E>" (the one in the .bind.apply part).

** UPDATE **

I discovered that the problem occurs when trying to create a new generic instance with a non-empty diamond operator. That is, `new Array<E>(...)` gives an error but `new Array<>(...)` doesn't. So I have a workaround - maybe it's an issue in the Java to TS transpiler portion? Or something that TS should accept maybe?

**Comment by renaudpawlak** [comment] 2016-12-23 09:40
Thanks for that very complete report. There is clearly a bug here (I can't even compile your example in the sandbox). I will investigate when possible.

**Comment by renaudpawlak** [comment] 2017-07-24 15:07
Actually testing with the current version, I have not been able to reproduce that bug, simply because ``new Array<E>(arr.slice())`` does not compile in Java. It makes sense to me, so maybe it was a flaw in the v1 API. I have added [your code as a test](https://github.com/cincheo/jsweet/blob/master/transpiler/src/test/java/source/generics/SliceOfArrays.java), so you can check it it makes sense to you too... I am closing this bug (to be reopened if not fixed in v2).

**Closed by renaudpawlak** 2017-07-24 15:07 UTC
Labels: bug
