### ISSUE TITLE
Deserializing to specific Java objects

### ISSUE THREAD

**Issue by msx80** [cincheo/jsweet#200] opened 2016-12-22 16:25 UTC
Hello, so i have my objects defined in Java (MyObject) which works perfectly. I'd like to store some instances into LocalStorage and to do so i have to (de)serialize them to strings of any kind. Is there a generic way to do this?
I can easily serialize it to JSON with JSON.stringify but when i do JSON.parse i obtain a generic Object, not MyObject (obviously). Is there something like Java serialization that gets your object back? Either inside JSweet or as a separate module?

**Comment by renaudpawlak** [comment] 2016-12-22 17:31
Duplicate of #188. Generic code to deserialize JSweet object is shared here: https://gist.github.com/renaudpawlak/4d1908a626ce2e0591c1a54bbe545ce5
Don't hesitate to create a lib for it if you wish :)

**Closed by renaudpawlak** 2016-12-22 17:31 UTC

**Comment by MrMjauh** [comment] 2018-05-09 12:47
Hello, the gist does not work for newer version since alot of the code/classes have been moved or removed. Any chance you could update the gist :)?

**Comment by lgrignon** [comment] 2018-05-09 21:03
I just published an updated version of how to properly deserialize with JSweet 2.2. Hope it will be useful for you ;)

https://github.com/lgrignon/jsweet-model-dto-json-deserialization

**Comment by MrMjauh** [comment] 2018-05-10 06:44
Thank you a million :D, was trying to do it by reading through the source code and finding all the classes! Had some help from the release notes. Thanks!

**Comment by lgrignon** [comment] 2018-05-10 08:05
you are welcome :)
