### ISSUE TITLE
Support for Java 9 (was Error in the compilation of the quickstart example)

### ISSUE THREAD

**Issue by Cyxo** [cincheo/jsweet#263] opened 2017-04-21 21:53 UTC
Hello,

I didn't change anything in the quickstart, I just cloned it from github, and I get this error while running "mvn generate-sources" : `Cannot assign configuration entry 'module' to 'class org.jsweet.transpiler.ModuleKind' from 'null', which is of type class java.lang.String`

Here is full stacktrace :
`
Cause: Cannot assign configuration entry 'module' to 'class org.jsweet.transpiler.ModuleKind' from 'null', which is of type class java.lang.String
[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error configuring: org.jsweet:jsweet-maven-plugin. Reason: Unable to parse the created DOM for plugin configuration
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:723)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:556)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:535)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
        at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:520)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.PluginConfigurationException: Error configuring: org.jsweet:jsweet-maven-plugin. Reason: Unable to parse the created DOM for plugin configuration
        at org.apache.maven.plugin.DefaultPluginManager.populatePluginFields(DefaultPluginManager.java:1363)
        at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:724)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:468)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
        ... 17 more
Caused by: org.codehaus.plexus.component.configurator.ComponentConfigurationException: Cannot assign configuration entry 'module' to 'class org.jsweet.transpiler.ModuleKind' from 'null', which is of type class java.lang.String
        at org.codehaus.plexus.component.configurator.converters.AbstractConfigurationConverter.fromExpression(AbstractConfigurationConverter.java:149)
        at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.fromConfiguration(ObjectWithFieldsConverter.java:80)
        at org.codehaus.plexus.component.configurator.converters.ComponentValueSetter.configure(ComponentValueSetter.java:247)
        at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.processConfiguration(ObjectWithFieldsConverter.java:137)
        at org.codehaus.plexus.component.configurator.BasicComponentConfigurator.configureComponent(BasicComponentConfigurator.java:56)
        at org.apache.maven.plugin.DefaultPluginManager.populatePluginFields(DefaultPluginManager.java:1357)
        ... 20 more
`

I'm on a linux machine and maven is new to me (I used to do with gradle or jdk directly before and it worked like a charm).

Can you help me ?

**Comment by renaudpawlak** [comment] 2017-04-23 18:37
I have just tried it again with a clean Maven repo under Mac OS and it works fine. Could you provide the full trace?

**Comment by lgrignon** [comment] 2017-04-24 06:16
It may be related to your maven version, could you please also provide the result of the following commands:
```
mvn -version
which mvn
```

Thanks

**Comment by p4ulolol** [comment] 2017-04-26 11:21
Here is full trace :
`
+ Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Building JSweet quick start
[INFO]    task-segment: [generate-sources]
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Failed to configure plugin parameters for: org.jsweet:jsweet-maven-plugin:1.2.0



Cause: Cannot assign configuration entry 'module' to 'class org.jsweet.transpiler.ModuleKind' from 'null', which is of type class java.lang.String
[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error configuring: org.jsweet:jsweet-maven-plugin. Reason: Unable to parse the created DOM for plugin configuration
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:723)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:556)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:535)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
	at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:520)
	at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
	at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
	at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.PluginConfigurationException: Error configuring: org.jsweet:jsweet-maven-plugin. Reason: Unable to parse the created DOM for plugin configuration
	at org.apache.maven.plugin.DefaultPluginManager.populatePluginFields(DefaultPluginManager.java:1363)
	at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:724)
	at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:468)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
	... 17 more
Caused by: org.codehaus.plexus.component.configurator.ComponentConfigurationException: Cannot assign configuration entry 'module' to 'class org.jsweet.transpiler.ModuleKind' from 'null', which is of type class java.lang.String
	at org.codehaus.plexus.component.configurator.converters.AbstractConfigurationConverter.fromExpression(AbstractConfigurationConverter.java:149)
	at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.fromConfiguration(ObjectWithFieldsConverter.java:80)
	at org.codehaus.plexus.component.configurator.converters.ComponentValueSetter.configure(ComponentValueSetter.java:247)
	at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.processConfiguration(ObjectWithFieldsConverter.java:137)
	at org.codehaus.plexus.component.configurator.BasicComponentConfigurator.configureComponent(BasicComponentConfigurator.java:56)
	at org.apache.maven.plugin.DefaultPluginManager.populatePluginFields(DefaultPluginManager.java:1357)
	... 20 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2 seconds
[INFO] Finished at: Wed Apr 26 11:12:04 UTC 2017
[INFO] Final Memory: 11M/38M
[INFO] ------------------------------------------------------------------------
`

And here are the results of the commands :
`
paulolol:~/workspace/jsweet-quickstart (master) $ mvn -v
Apache Maven 2.2.1 (rdebian-14)
Java version: 9-ea
Java home: /usr/lib/jvm/java-9-oracle
Default locale: en, platform encoding: UTF-8
OS name: "linux" version: "4.9.17-c9" arch: "amd64" Family: "unix"
paulolol:~/workspace/jsweet-quickstart (master) $ which mvn
/usr/bin/mvn
`

**Comment by renaudpawlak** [comment] 2017-04-26 11:32
Ok. You have an uncommon configuration. Please update Maven to Maven 3.x (that's for sure a problem).
Also, I am not sure it will work with Java 9 but that will be an interesting test.

**Comment by lgrignon** [comment] 2017-04-26 11:57
Yeah, definitively the Maven version is to blame.

**Comment by p4ulolol** [comment] 2017-04-26 11:57
Ok, Maven 3.0.5 installed. And of course a new error, but this time with jsweet I guess :
```
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building JSweet quick start 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- jsweet-maven-plugin:1.2.0:jsweet (generate-js) @ jsweet-quickstart ---
[INFO] JSweet transpiler version 1.2.0 (build date: 2016-12-16 11:22:33)
WARN: candy j4ts:0.2.0-SNAPSHOT was generated for a different version of the transpiler (current:1.2.0, candy:1.1.1)
ERROR: package jsweet.dom does not exist at /home/ubuntu/workspace/jsweet-quickstart/src/main/java/quickstart/QuickStart.java(3)
2017-04-26 11:52:08.008 ERROR JSweetTranspiler:373 - /home/ubuntu/workspace/jsweet-quickstart/src/main/java/quickstart/QuickStart.java:3: error: package jsweet.dom does not exist
import static jsweet.dom.Globals.alert;
                        ^
ERROR: static import only from classes and interfaces at /home/ubuntu/workspace/jsweet-quickstart/src/main/java/quickstart/QuickStart.java(3)
2017-04-26 11:52:08.008 ERROR JSweetTranspiler:373 - /home/ubuntu/workspace/jsweet-quickstart/src/main/java/quickstart/QuickStart.java:3: error: static import only from classes and interfaces
import static jsweet.dom.Globals.alert;
^
ERROR: package def.jquery does not exist at /home/ubuntu/workspace/jsweet-quickstart/src/main/java/quickstart/QuickStart.java(4)
2017-04-26 11:52:08.008 ERROR JSweetTranspiler:373 - /home/ubuntu/workspace/jsweet-quickstart/src/main/java/quickstart/QuickStart.java:4: error: package def.jquery does not exist
import static def.jquery.Globals.$;
                        ^
ERROR: static import only from classes and interfaces at /home/ubuntu/workspace/jsweet-quickstart/src/main/java/quickstart/QuickStart.java(4)
2017-04-26 11:52:08.008 ERROR JSweetTranspiler:373 - /home/ubuntu/workspace/jsweet-quickstart/src/main/java/quickstart/QuickStart.java:4: error: static import only from classes and interfaces
import static def.jquery.Globals.$;
^
ERROR: package jsweet.lang does not exist at /home/ubuntu/workspace/jsweet-quickstart/src/main/java/quickstart/QuickStart.java(9)
2017-04-26 11:52:08.008 ERROR JSweetTranspiler:373 - /home/ubuntu/workspace/jsweet-quickstart/src/main/java/quickstart/QuickStart.java:9: error: package jsweet.lang does not exist
import jsweet.lang.Array;
                  ^
[ERROR] transpilation failed
org.apache.maven.plugin.MojoFailureException: transpilation failed with 5 error(s) and 1 warning(s)
	at org.jsweet.AbstractJSweetMojo.transpile(AbstractJSweetMojo.java:337)
	at org.jsweet.JSweetMojo.execute(JSweetMojo.java:41)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:520)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.998s
[INFO] Finished at: Wed Apr 26 11:52:08 UTC 2017
[INFO] Final Memory: 12M/42M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jsweet:jsweet-maven-plugin:1.2.0:jsweet (generate-js) on project jsweet-quickstart: transpilation failed: transpilation failed with 5 error(s) and 1 warning(s) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jsweet:jsweet-maven-plugin:1.2.0:jsweet (generate-js) on project jsweet-quickstart: transpilation failed
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:520)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: transpilation failed
	at org.jsweet.AbstractJSweetMojo.transpile(AbstractJSweetMojo.java:351)
	at org.jsweet.JSweetMojo.execute(JSweetMojo.java:41)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: org.apache.maven.plugin.MojoFailureException: transpilation failed with 5 error(s) and 1 warning(s)
	at org.jsweet.AbstractJSweetMojo.transpile(AbstractJSweetMojo.java:337)
	... 22 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by lgrignon** [comment] 2017-04-26 12:03
Could you please provide the full command you are typing, and check that jquery dependency is correctly declared in the pom.xml (I guess it is since since you only cloned the quickstart repo)

**Comment by p4ulolol** [comment] 2017-04-26 12:16
I juste followed the steps in the "Getting Started" section in the README of this repo, and the error happens just after the `mvn generate-sources` command. I didn't change anything in the pom.xml file and I don't see anything about jquery in it.

**Comment by renaudpawlak** [comment] 2017-04-26 12:38
In your errors, everything happens like if the dependencies in the pom.xml were not found. You are not the first one to report similar Maven issues on some systems. It could be because you upgraded Maven starting from an older version.

You could try to ``rm -rf ~/.m2`` just in case (will clean your local Maven repo/conf), and/or ``mvn -U generate-sources`` (-U will force all the dependencies to be updated).

**Comment by p4ulolol** [comment] 2017-04-26 12:42
That didn't work, still the same error

**Comment by renaudpawlak** [comment] 2017-04-26 13:05
Ok. A couple messages before, you said you did not see anything about jquery in your pom.xml. This could be a clue. The pom.xml contains a jquery dependency at the end, as shown here: https://github.com/cincheo/jsweet-quickstart/blob/master/pom.xml#L133

Also, according to your trace, it looks that JSweet is not in verbose mode, which does not make sense because in the pom.xml, JSweet is in verbose mode, as shown here: https://github.com/cincheo/jsweet-quickstart/blob/master/pom.xml#L65

To me, these could be clues that you changed your pom.xml, or even that you did not clone the right project. Could you double check (maybe clone again) the quick start project? https://github.com/cincheo/jsweet-quickstart

**Comment by p4ulolol** [comment] 2017-04-26 19:19
Sorry, here it is with the verbose. And I was a bit blind because I did not see the line with jquery at the bottom of the pom.xml file. [trace.txt](https://github.com/cincheo/jsweet/files/959512/trace.txt)

**Comment by renaudpawlak** [comment] 2017-04-27 04:54
So, you see in the trace, JSweet tells you which classpath it is going to use. Could you check the to most important jars:

- /home/ubuntu/.m2/repository/org/jsweet/candies/jsweet-core/1.2.0-SNAPSHOT/jsweet-core-1.2.0-SNAPSHOT.jar
- /home/ubuntu/.m2/repository/org/jsweet/candies/jquery/1.10.0-SNAPSHOT/jquery-1.10.0-SNAPSHOT.jar

Just check that they are here and that the contain the classes that the build tells you are missing (jar -tf xxx.jar).

If they are ok, then I don't know, and I would bet on a problem with Java 9. I would then recommend switching back to Java 8 for now.

**Comment by lgrignon** [comment] 2017-04-28 11:54
I just checked on another machine, and it works too. Not quite the same configuration though.
I would for sure try to install the latest maven 3.3, and use Java 8 (on Ubuntu you can switch easily from one jdk to another). In addition, I notice you use a standard jvm, I think you need the JDK to run JSweet, or at least specify its path if not deduced. @renaudpawlak do you confirm?
```
λ mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: C:\Users\shae\dev\apache-maven-3.3.9
Java version: 1.8.0_71, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_71\jre
Default locale: fr_FR, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"
```

**Comment by p4ulolol** [comment] 2017-04-28 18:48
Ok, downgrading to Java 8 made it work. Thank you for your help

**Comment by lgrignon** [comment] 2017-04-28 19:32
Ok, good news, we let this issue open to make JSweet compatible with Java 9

**Comment by regrog** [comment] 2019-10-16 10:48
Any news about Java 9+ compatibility?

**Comment by lucgirardin** [comment] 2019-10-16 11:14
There seems to be some activity: check out #519.

**Comment by lgrignon** [comment] 2019-10-25 19:43
Duplicate of https://github.com/cincheo/jsweet/issues/519, indeed :)

**Closed** 2019-10-25 19:43 UTC
Labels: enhancement
