### ISSUE TITLE
Initialization fails when super constructor calls overridden method

### ISSUE THREAD

**Issue by alievrenkut** [cincheo/jsweet#377] opened 2017-09-26 14:39 UTC
You can try this case by https://github.com/alievrenkut/jsweet-quickstart If we write:
```
public class Parent {
	Object parentField;
	public Parent(Object field){
		setField(field);
	}
	public void setField(Object field) {
		this.parentField = field;
	}
}
```

```
public class Child extends Parent{
	Object childField;
	public Child(Object field)
	{
		super(field);
	}
	@Override
	public void setField(Object field) {
		super.setField(field);
		childField = field;
	}
}
```

This generates:
```
    var Child = (function (_super) {
        __extends(Child, _super);
        function Child(field) {
            var _this = _super.call(this, field) || this;
            _this.childField = null;
            return _this;
        }
```

Which makes childField null because Child.setField is called before line
`            _this.childField = null;`
 which breaks implementation.

**Comment by renaudpawlak** [comment] 2017-10-06 16:41
Tricky one, but great one! I think I know how to fix it. I'll give a stab at it when possible.

**Comment by renaudpawlak** [comment] 2017-10-11 06:30
This should be fixed.

**Closed by renaudpawlak** 2017-10-11 06:30 UTC
Labels: bug

**Comment by thw0rted** [comment] 2018-04-25 11:14
Has there been a release since this fix?  Is there one planned soon?  The latest I see [here](http://repository.jsweet.org/artifactory/webapp/#/artifacts/browse/tree/General/libs-snapshot-local/org/jsweet/jsweet-core) lines up with the quickstart, `5-20170726`.

**Comment by lgrignon** [comment] 2018-04-26 22:06
The JSweet transpiler's snapshot has been redeployed several times (AFAIK the fix was made in the transpiler, not the [JSweet core candy](http://repository.jsweet.org/artifactory/webapp/#/artifacts/browse/tree/General/libs-release-local/org/jsweet/jsweet-core))
Did you encounter this problem?

**Comment by thw0rted** [comment] 2018-04-27 07:15
As I said in #431, the issue is that I was using the maven plugin 2.0.0, based on the quickstart.  Is a new (non-snapshot) plugin release planned soon?
