### ISSUE TITLE
StringBuilder.append cannot be used in a fluent way

### ISSUE THREAD

**Issue by travelbasys** [cincheo/jsweet#381] opened 2017-09-30 18:52 UTC
The following code does not compile in JSweet.
```
package quickstart;
public class TestStringBuilder {
	public static void main(String[] args) {
		StringBuilder sb = new StringBuilder();
 		sb.append("abc").append("DEF");         // <--- Error
		System.out.println(sb.toString());
	}
}
```
It is legal to use the <code>append</code> method in a fluent way, so it should print <code>abcDEF</code> on the console.
But the compiler/Eclipse reports <code>Property 'str' does not exist on type 'string'</code>.

Here is the transpiler output:
```
/* Generated from Java with JSweet 2.0.0-rc1 - http://www.jsweet.org */
namespace quickstart {
    export class TestStringBuilder {
        public static main(args : string[]) {
            console.info("Begin TestStringBuilder");
            let sb : { str: string } = { str: "", toString: function() { return this.str; } };
            /* append */(sb => sb.str = sb.str.concat(<any>"DEF"))(/* append */(sb => sb.str = sb.str.concat(<any>"abc"))(sb));
            console.info(/* toString */sb.str);
            console.info("End");
        }
    }
    TestStringBuilder["__class"] = "quickstart.TestStringBuilder";

}

quickstart.TestStringBuilder.main(null);

```
And
```
/* Generated from Java with JSweet 2.0.0-rc1 - http://www.jsweet.org */
var quickstart;
(function (quickstart) {
    var TestStringBuilder = (function () {
        function TestStringBuilder() {
        }
        TestStringBuilder.main = function (args) {
            console.info("Begin TestStringBuilder");
            var sb = { str: "", toString: function () { return this.str; } };
            /* append */ (function (sb) { return sb.str = sb.str.concat("DEF"); })(/* append */ (function (sb) { return sb.str = sb.str.concat("abc"); })(sb));
            console.info(/* toString */ sb.str);
            console.info("End");
        };
        return TestStringBuilder;
    }());
    quickstart.TestStringBuilder = TestStringBuilder;
    TestStringBuilder["__class"] = "quickstart.TestStringBuilder";
})(quickstart || (quickstart = {}));
quickstart.TestStringBuilder.main(null);

```
The browser (Chrome) says:

> Uncaught TypeError: Cannot read property 'concat' of undefined
>     at TestStringBuilder.js:9
>     at Function.TestStringBuilder.main (TestStringBuilder.js:9)
>     at TestStringBuilder.js:17

Needless to say, using <code>append</code> in a non-fluent way
```
sb.append("abc";
sb.append("DEF");
```
works nicely.

The problem seems to be the fat arrow function 
<code>/\* append \*/(sb => sb.str = sb.str.concat(&lt;any>"some string"))</code>.

It returns <code>sb.str</code> but it should rather be returning its input <code>sb</code>.

Using the comma operator and changing the code to
<code>/\* append \*/(sb => sb.str = sb.str.concat(&lt;any>"some string")<b>, sb</b>)</code>
should do the trick.

Regards.

**Comment by travelbasys** [comment] 2017-09-30 19:42
Well, it looks like this problem has already been fixed.

I just discovered method <code>substituteMethodInvocationOnStringBuilder</code> in class <code>RemoveJavaDependenciesAdapter</code>.

It seems to generate the fat arrow function in the following shape:
<code>/\* append \*/(sb => { sb.str = sb.str.concat(<any>"some string"); <b>return sb; </b>} )</code>

Which is fine, too.

Obviously the fix hasn't made it yet into my jars.
JSweet-quickstart, in which I was trying out my example, uses <code>jsweet-core-5-20170726.jar</code> which is probably not what we really want.

Regards.

**Comment by renaudpawlak** [comment] 2017-10-06 11:04
Hi @travelbasys. Sorry for late answer but I have been terribly busy.
The problem does not come from ``jsweet-core-5-20170726.jar`` because this jar only contains the JS and JSweet APIs. You don't have the latest development version but it does not matter that much. Here the problem is probably that you don't use the latest JSweet transpiler version. You log says you are using 2.0.0-rc1. I don't remember when this bug was fixed, but please use version 2.0.0. Or if it still does not work, try out version 2.0.1-SNAPSHOT just to check if it is fixed in the master (if not, there is obviously a big problem and we will investigate more).
Thanks!

**Closed by renaudpawlak** 2017-10-06 11:04 UTC

**Comment by HubertKauker** [comment] 2017-10-06 14:20
Hm.
Doesn't help me.
I installed the current _JSweet Eclipse plugin_ and cloned the _jsweet-quickstart_ project from GitHub.
I am not aware my transpiler version can be configured anywhere.
So, if I'm using **2.0.0-rc1**, that's fine, but that was decided elsewhere.
How and where could I configure a different version?

You do not want to see my POM, do you?
Here it is.
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>org.jsweet</groupId>
	<artifactId>jsweet-quickstart</artifactId>
	<version>2.0.0</version>
	<name>JSweet v2 quick start</name>
	<description>A simple project structure to get started with JSweet v2</description>
	<developers>
		<developer>
			<id>rpawlak</id>
			<name>Renaud Pawlak</name>
			<email>renaud.pawlak@gmail.com</email>
		</developer>
	</developers>
	<licenses>
		<license>
			<name>The Apache Software License, Version 2.0</name>
			<url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
			<distribution>repo</distribution>
		</license>
	</licenses>
	<pluginRepositories>
		<pluginRepository>
			<id>jsweet-plugins-release</id>
			<name>plugins-release</name>
			<url>http://repository.jsweet.org/artifactory/plugins-release-local</url>
		</pluginRepository>
		<pluginRepository>
			<snapshots />
			<id>jsweet-plugins-snapshots</id>
			<name>plugins-snapshot</name>
			<url>http://repository.jsweet.org/artifactory/plugins-snapshot-local</url>
		</pluginRepository>
	</pluginRepositories>
	<repositories>
		<repository>
			<id>jsweet-central</id>
			<name>libs-release</name>
			<url>http://repository.jsweet.org/artifactory/libs-release-local</url>
		</repository>
		<repository>
			<snapshots />
			<id>jsweet-snapshots</id>
			<name>libs-snapshot</name>
			<url>http://repository.jsweet.org/artifactory/libs-snapshot-local</url>
		</repository>
	</repositories>
	<build>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.1</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
					<fork>true</fork>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.jsweet</groupId>
				<artifactId>jsweet-maven-plugin</artifactId>
				<version>2.0.0</version>
				<configuration>
					<verbose>true</verbose>
					<tsOut>target/ts</tsOut>
					<outDir>target/js</outDir>
					<candiesJsOut>webapp</candiesJsOut>
					<targetVersion>ES3</targetVersion>
				</configuration>
				<executions>
					<execution>
						<id>generate-js</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>jsweet</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
		<pluginManagement>
			<plugins>
				<!--This plugin's configuration is used to store Eclipse m2e settings 
					only. It has no influence on the Maven build itself. -->
				<plugin>
					<groupId>org.eclipse.m2e</groupId>
					<artifactId>lifecycle-mapping</artifactId>
					<version>1.0.0</version>
					<configuration>
						<lifecycleMappingMetadata>
							<pluginExecutions>
								<pluginExecution>
									<pluginExecutionFilter>
										<groupId>
											org.jsweet
										</groupId>
										<artifactId>
											jsweet-maven-plugin
										</artifactId>
										<versionRange>
											[1.0.0,)
										</versionRange>
										<goals>
											<goal>jsweet</goal>
										</goals>
									</pluginExecutionFilter>
									<action>
										<ignore></ignore>
									</action>
								</pluginExecution>
							</pluginExecutions>
						</lifecycleMappingMetadata>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
	<dependencies>
		<dependency>
			<groupId>org.jsweet</groupId>
			<artifactId>jsweet-core</artifactId>
			<version>5-20170726</version>
		</dependency>
<!--		<dependency>
			<groupId>org.jsweet.candies</groupId>
			<artifactId>node</artifactId>
			<version>7.5.0-20170726</version>
		</dependency>-->
		<dependency>
			<groupId>org.jsweet.candies</groupId>
			<artifactId>jquery</artifactId>
			<version>1.10.0-20170726</version>
		</dependency>
	</dependencies>
</project>
```

**Comment by renaudpawlak** [comment] 2017-10-06 15:54
Oh. I see... The transpiler version is decided by the Eclipse plugin :)
That's why. I did now know you were using the Eclipse plugin.
Ok. I'll update the plugin and I'll tell you when done.

**Comment by renaudpawlak** [comment] 2017-10-06 16:00
Please note that the Eclipse plugin is not required. You can really have the same features with the Maven plugin, but with more options and more flexible. That said I fully understand if you prefer to use the Eclipse plugin :)

**Comment by lgrignon** [comment] 2017-10-06 16:07
That being said, you can use the version 2.0.1-SNAPSHOT of the JSweet Maven plugin, to enjoy the latest features.

**Comment by renaudpawlak** [comment] 2017-10-06 16:29
Ok. I have updated the plugin with version 2.0.0 (hopefully if I did not mess up). Tell me if it still does not work. I will then update with latest snapshot.

**Comment by renaudpawlak** [comment] 2017-10-06 16:31
NOTE: this raises the issue that maybe the adapters should be released separately from the transpiler. In an ideal world they should be available as Maven artifacts.
Ummm. That's the first time I think about this one.

**Comment by travelbasys** [comment] 2017-10-07 22:10
Do you mean that the jsweet-eclipse-plugin was updated to contain transpiler version 2.0.0 now?

Perhaps you must do a little more...
Because I find that jsweet-eclipse feature is still at version **0.9.5.201708121132**.
Trying to update it in Eclipse from the official update site did "nothing".

You may have added the 2.0.0 transpiler to the internal jar, but obviously no complete deployment of the entire feature has been done, yet.
The update site does not show any newer version than the one above.

- Thanks for putting so much work into such a small and unimportant issue.
- :-)

And thanks for mentioning that I might use Maven to obtain correctly transpiled code.
However, nothing beats the elegance of automatic building in Eclipse, and as soon as  incremental building works it should be much faster than full Maven builds, too.
At the present time, building of even a single class is rather slowish, but actually I don't care much at the moment.
