### ISSUE TITLE
"Illegal overloading" with String[] constructor

### ISSUE THREAD

**Issue by CrushedPixel** [cincheo/jsweet#154] opened 2016-07-30 11:00 UTC
Consider the following Object:

    public class SomeObject {
        public SomeObject() {}
        public SomeObject(String[] stringArray) {}
    }

When transpiling `SomeObject` using `JSweet 1.2.0-SNAPSHOT`,  
calling `new SomeObject(new String[] {"any", "string", "array"});` causes the Runtime Javascript error "Illegal overloading" which you explicitly throw after checking for the type of every input object.  

This is because `typeof stringArray == 'Array'` evaluates to `false`, as `stringArray` is `Object` at runtime.

My workaround was to remove the empty constructor in the Object, so it doesn't do this overloading check at all, but this is a rather critical bug.

**Comment by renaudpawlak** [comment] 2016-08-01 17:17
You are right. It is a critical bug... probably a regression because it seemed to work at some point. Thank you for reporting.

**Comment by renaudpawlak** [comment] 2016-10-22 16:45
Apparently this issue was fixed in the current snapshot. I have just added a test to make sure everything is fine. Please tell me if it persists with you because in that case it might reflect a trickier issues. Thanks.

**Closed by renaudpawlak** 2016-10-22 16:45 UTC
Labels: bug
