### ISSUE TITLE
is it possible to generate ts code that is compatible with TS strict mode?

### ISSUE THREAD

**Issue by xdenser** [cincheo/jsweet#680] opened 2021-02-19 09:10 UTC
In Java all non-primitive variables are 'nullable', this is not so in TS in strict mode.
If some (field or variable) is declared as 
  `foo: string;`
You cannot just assign null or undefined to `foo`.
To be compatible it should look like
` foo: string | null = null;`
or
`foo?: string | null;`
The same applies to all no-primitive function return types - they are nullable. Well propper implementation could include some analysis - if the code actually can return null.
Also "meta" informations like this (also not valid in ts strict mode):
`SomeClass["__class"] = "my.package.ParsedDateFormat";`
may be done like this 
`static __class = "my.package.ParsedDateFormat"` 
but in class body.

**Comment by lgrignon** [comment] 2021-04-11 08:52
Duplicate of https://github.com/cincheo/jsweet/issues/680

**Closed by lgrignon** 2021-04-11 08:52 UTC
