### ISSUE TITLE
Maven clean phase is uncomplete

### ISSUE THREAD

**Issue by Eclesia** [cincheo/jsweet#291] opened 2017-05-31 18:47 UTC
When building a project with the candy maven plugin it generates a javascript folder in the root folder.
It would be nice if this folder could be in the target directory, this way a call to `mvn clean` would delete it otherwise it is never removed.

(With over 100 modules in my project this leaves a big mess)

**Comment by renaudpawlak** [comment] 2017-05-31 19:11
Well, you just have to set the out and tsout options to generate your js and ts files in ``target`` (typically ``target/js`` and ``target/ts``). Almost everything is customizable in the Maven plugin (see the option list [there](https://github.com/lgrignon/jsweet-maven-plugin)).

However, I believe that while releasing the v2, it would be a good thing to improve the Maven plugin... I see at least two ways to improve it:

1. make all build files to be generated in target by default
2. add an option to automatically set the generated js and d.ts files in the META-INF directory (in order to simplify candy creation)...

That would be great improvements, not only for JSweet beginners.

**Comment by lgrignon** [comment] 2017-05-31 20:17
Thanks for the answer. 
@Eclesia Additionally, you can bind the clean phase to the JSweet clean mojo which is in charge of cleaning TypeScript and JavaScript output directory.

@renaudpawlak +1 for an easy "candy mode" option and enhanced defaults. Should we create other issues for this?

**Comment by Eclesia** [comment] 2017-05-31 21:59
and if it could generate the candy-metadata.json on it's own too if it's missing that would be nice.

**Comment by lgrignon** [comment] 2017-06-04 17:52
I close this issue.
1) I enhanced the defaults in the JSweet Maven and Gradle plugins.
2) I created a feature request on the maven plugin's project in order to add the candy mode option: 
https://github.com/lgrignon/jsweet-maven-plugin/issues/26

Thanks for your contribution!

**Closed by lgrignon** 2017-06-04 17:52 UTC
Labels: discussion, enhancement, feature request

**Comment by renaudpawlak** [comment] 2017-06-05 06:24
Now that I think of it, I think that all JSweet Mojo's defaults values should be null, so that JSweet can make a difference between values that were set by the user and the ones that are default. This is really important to allow us to handle jsweetconfig.json properly.

**Comment by lgrignon** [comment] 2017-06-05 07:41
Could you open an issue on the maven plugin's project, explaining how to handle jsweetconfig.json?

**Comment by thw0rted** [comment] 2018-04-18 14:02
FYI, the quickstart still configures `candiesJsOut` at top level, not under `target`.

**Comment by lgrignon** [comment] 2018-04-18 21:55
It is the intended behaviour. It puts candies js to the webapp folder
https://github.com/cincheo/jsweet-quickstart/blob/master/pom.xml#L68

What's the point?

**Comment by thw0rted** [comment] 2018-04-19 07:58
That's a good point, but the complaint was that `mvn clean` "misses" some build artifacts.  I guess I'm a little confused about the layout of the POM .  When you run `generate-sources` it will unpack the candies into `webapp` so that the demo page can reference them, which makes sense, but now you have build artifacts (unpacked candies) in a source directory (`webapp`, which has your web assets).

Now, I've been out of the Java / Maven world for a few years, but it seems to me that maybe `index.html` and `logo.png` should live somewhere under `src` (`src/main/webapp`?), getting copied to somewhere under `target` on build, which would also be the value of `candiesJsOut`.  This would allow `clean` to simply wipe the `target` directory and remove all build artifacts.  (This would also keep you from accidentally adding an unpacked candy to Git, since you already have `target` in `.gitignore`.)
