### ISSUE TITLE
Extra parentheses around while loop condition

### ISSUE THREAD

**Issue by chrismiddleton** [cincheo/jsweet#197] opened 2016-12-14 03:24 UTC
The transpiler seems to be generating extra parentheses around the while loop condition in the TypeScript output.

The following code:

	package org.jsweet;

	import static jsweet.dom.Globals.*;

	public class HelloWorld {
		public static void main(String[] args) {
			int i = 3;
			int len = 4;
			while (i < len) {
				System.out.println(i++);
			}
		}
	}

generates a while loop with an extra set of parentheses.

	namespace org.jsweet {
		export class HelloWorld {
			public static main(args : string[]) {
				var i : number = 3;
				var len : number = 4;
				while((i < len)){
					console.info(i++);
				};
			}
		}
	}

It seems to run OK on its own, but when part of the larger program I'm trying to compile, I get this error which points to the first closing parenthesis (the extra one) in the TypeScript:

    2016-12-13 21:24:29.029 INFO  JSweetTranspiler:1070 - MyFile.ts(144,32): error TS1005: ',' expected.

**Comment by renaudpawlak** [comment] 2016-12-15 07:53
Unless I miss something, by no means extra-parenthesis could cause such problem as the one reported. There is most probably another syntax error in the file that leads to this one. You would need to investigate more and try to locate the root cause of the problem. Don't hesitate to share the generated code.

I am closing this issue until the root issue gets identified.

**Closed by renaudpawlak** 2016-12-15 07:53 UTC
